name: Sync and Run Script

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone another GitHub repo (not owned by you)
      - name: Checkout another repository
        run: |
          whoami
          echo ${{ secrets.USERPWD }} | sudo -S apt update
          echo ${{ secrets.USERPWD }} | sudo -S apt upgrade -y && apt install dpkg -y
          git clone https://github.com/tavrick19654-oss/Silica.git copyme

      # Step 2: Clone your own repository
      - name: Checkout your own repository
        run: |
          git clone https://github.com/tavrick19654-oss/tavrick19654-oss.github.io.git myrepo
        

      # Step 4: Go to the other repo's folder
      - name: Change directory to other repo's folder
        run: |
          cd copyme/  # Replace with the actual folder in the other repo
          pip install -r requirements.txt --break-system-packages
          chmod +x setup.sh
          ./setup.sh
          cd ..

      # Step 7: Go back to your repo and copy files to the other repo
      - name: Copy files from your repo to the other repo
        run: |
          cp -r /home/runner/work/tavrick19654-oss.github.io/tavrick19654-oss.github.io/myrepo/Package/ /home/runner/work/tavrick19654-oss.github.io/tavrick19654-oss.github.io/copyme/Packages/

      # Step 8: Run python3 index.py in the other repo
      - name: Run index.py in the other repo
        run: |
          cd copyme/
          python3 index.py

      # Step 9: Finalize
      - name: Finalize
        run: |
          cd /home/runner/work/tavrick19654-oss.github.io/tavrick19654-oss.github.io/myrepo/debs/
          gzip -c *.deb > Packages.gz
